ProyectoFinal/BLSC/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path
from BLSC.views import home_view
from .views import signin_view, signinok_view, login_view, acercademi_view, editarperfil_view


app_name = "BLSC"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('acercademi/', acercademi_view, name='acercademi'),
##### URLs PARA SIGN IN, LOGIN Y LOGOUT
    path('signin/', signin_view, name='signin'),
    path('signinok/', signinok_view, name='signinok'),
    path('login/', login_view, name='login'),
    path('logout/', LogoutView.as_view(template_name="BLSC/logout.html"), name='logout'),
##### EDITAR USUARIO
    path('editarperfil/', editarperfil_view, name='editarperfil'),
]

ProyectoFinal/ProyectoFinal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("BLSC.urls")),
]


from django.conf import settings
from django.conf.urls.static import static

url_patterns_for_media = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns = urlpatterns + url_patterns_for_media

ProyectoFinal/BLSC/models.py
from django.db import models
from django.contrib.auth.models import User


class Obra(models.Model):
    ObraSeleccion = (
    ('poesía','Poesía'),
    ('ficción', 'Ficción'),
    ('no-ficción','No-ficción'),
    ('drama','Drama'),
    ('ensayo','Ensayo'),
    ('otro', 'Otro'),
    )
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    titulo = models.CharField(max_length=200)
    tipo = models.CharField(max_length=15, choices=ObraSeleccion, default='otro')
    autor = models.CharField(max_length=40)
    año = models.IntegerField() 
    fechaPublicacion = models.DateTimeField(auto_now_add=True)
    descripcion = models.TextField(null=True, blank=True)
    emailUsuario = models.EmailField()
    imagenObra = models.ImageField(null=True, blank=True, upload_to="imagenes/")

    class Meta:
        ordering = ['usuario', '-fechaPublicacion']

    def __str__(self):
        return self.titulo





class Avatar(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.FileField(upload_to="media/avatares", null=True, blank=True)

    def __str__(self):
        return f"{self.user} - {self.imagen}"
    




class Perfil(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    descripcion = models.CharField(max_length=2200)

    def __str__(self):
        return f"{self.usuario}"





class Post(models.Model):
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.FileField(upload_to="media/posts", null=True, blank=True)
    epigrafe = models.CharField(max_length=30)

    def __str__(self):
        return f"{self.epigrafe}"




class Comentario(models.Model):
    id = models.BigAutoField(primary_key=True)
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    texto = models.CharField(max_length=2200)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f"@{self.autor}: '{self.post}'"

ProyectoFinal/BLSC/forms.py
from django.contrib.auth.forms import UserCreationForm, UserModel
from django import forms
from django.contrib.auth.password_validation import MinimumLengthValidator

class NoMinimumLengthValidator(MinimumLengthValidator):
    def __init__(self, min_length=8):
        super().__init__(min_length)

    def validate(self, password, user=None):
        pass

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField()
    username = forms.CharField(max_length=20, label='Usuarix', widget=forms.TextInput(attrs={'class':'form-control'}))
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput(attrs={'class':'form-control'}), validators=[NoMinimumLengthValidator()])
    password2 = forms.CharField(label='Repetir Contraseña', widget=forms.PasswordInput(attrs={'class':'form-control'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Desactiva la verificación de contraseñas comunes
        self.fields['password1'].validators = []  # Esto desactiva la verificación de contraseñas comunes

    class Meta:
        model = UserModel
        fields = ["email", "username", "password1", "password2"]
        help_texts = {k: "" for k in fields}




class UserEditionFormulario(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repetir contraseña", widget=forms.PasswordInput)
    first_name = forms.CharField(label="Nombre")
    last_name = forms.CharField(label="Apellido")

    class Meta:
        model = UserModel
        fields = ["email", "password1", "password2", "first_name", "last_name"]
        help_texts = {k: "" for k in fields}

ProyectoFinal/BLSC/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, UserEditionFormulario
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate
from django.contrib.auth import login, authenticate
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import Avatar



##### HOME (INICIO):

def home_view(request):
    if request.user.is_authenticated:
        usuario = request.user
        avatar = Avatar.objects.filter(user=usuario).first()
        avatar_url = avatar.imagen.url if avatar is not None else ""
    else:
        avatar_url = ""

    return render(request, "BLSC/home.html", context={"avatar_url": avatar_url})



##### ABOUT:
def acercademi_view(request):
    return render(request, "BLSC/acercademi.html")



##### SIGN IN, LOGIN Y LOGOUT:

def signin_view(request):
    if request.method == "GET":
        return render(
            request,
            "BLSC/signin.html",
            {"form": CustomUserCreationForm()}
        )
    else:
        formulario = CustomUserCreationForm(request.POST)
        if formulario.is_valid():
            informacion = formulario.cleaned_data
            usuario = informacion["username"]
            formulario.save()

            # Construir la URL con el mensaje como parámetro
            url_signinok = reverse('BLSC:signinok') + f'?mensaje=Usuarix creadx: {usuario}'
            return redirect(url_signinok)
        else:
            return render(
                request,
                "BLSC/signin.html",
                {"form": formulario}
            )



def signinok_view(request):
    mensaje = request.GET.get('mensaje', '')
    return render(request, "BLSC/signinok.html", {"mensaje": mensaje})



def login_view(request):
    # Verifica si el usuario ya está autenticado
    if request.user.is_authenticated:
        return render(
            request,
            "BLSC/signinok.html",
            {"mensaje": f"¡¡Hola, @{request.user.username}!! Estás logeadx y puedes interactuar libremente en nuestra página."}
        )

    if request.method == "GET":
        return render(
            request,
            "BLSC/login.html",
            {"form": AuthenticationForm()}
        )
    else:
        formulario = AuthenticationForm(request, data=request.POST)

        if formulario.is_valid():
            informacion = formulario.cleaned_data
            usuario = informacion["username"]
            password = informacion["password"]

            modelo = authenticate(username=usuario, password=password)
            login(request, modelo)

            # Redirige al usuario a la página de inicio
            return redirect('BLSC:home')
        else:
            return render(
                request,
                "BLSC/login.html",
                {"form": formulario}
            )



##### EDITAR PERFIL:

@login_required
def editarperfil_view(request):

    usuario = request.user
    avatar = Avatar.objects.filter(user=usuario).last()
    avatar_url = avatar.imagen.url if avatar is not None else ""



    if request.method == "GET":


        valores_iniciales = {
            "email": usuario.email,
            "first_name": usuario.first_name,
            "last_name": usuario.last_name
        }


        formulario = UserEditionFormulario(initial=valores_iniciales)
        return render(
            request,
            "BLSC/editarperfil.html",
            context={"form": formulario, "usuario": usuario, "avatar_url": avatar_url}
        )
    else:
        formulario = UserEditionFormulario(request.POST)
        if formulario.is_valid():
            informacion = formulario.cleaned_data

            usuario.email = informacion["email"]

            usuario.set_password(informacion["password1"])

            usuario.first_name = informacion["first_name"]
            usuario.last_name = informacion["last_name"]
            usuario.save()
        return redirect("BLSC:home")

ProyectoFinal/BLSC/templates/BLSC/acercademi.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'BLSC/css/styles.css' %}" />
    <style>
        body {
            background-image: url('{% static 'BLSC/img/pclibro.jpg' %}');
            background-size: cover;
            background-position: center center;
            margin: 0;
            height: 100vh;
            display: flex;
            flex-direction: column;
            align-items: stretch;
            justify-content: flex-start;
            padding: 20px;
            color: #fff;
        }

        nav {
            margin-bottom: auto;
        }

        h2 {
            text-align: center;
            margin-top: 40px;
            font-family: 'Open Sans', sans-serif;
        }

        .card {
            background-color: #131514;
            color: #fff;
            padding: 60px;
            margin-bottom: 60px;
        }

        img {
            border: 2px solid #fff;
            max-width: 100%;
            height: auto;
            margin-bottom: 10px;
        }

        p {
            font-family: 'Open Sans', sans-serif;
            margin-bottom: 20px; /* Espacio adicional después del texto */
        }

        a {
            color: #fff;    
        }

        .site-heading h1 {
            color: #fff;
        }
    </style>
</head>
<body>

        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                {% if user.is_authenticated %}
                <span class="navbar-text" style="color: white;">||Usuarix en línea: {{ user.username }}||</span>            
                <a class="navbar-brand" href="{% url 'BLSC:logout' %}" style="margin-left: 100px;">CERRÁ SESIÓN</a>
                <a class="navbar-brand" href="{% url 'BLSC:home' %}" style="margin-left: 150px;">BLOG</a>
                <a class="navbar-brand" href="{% url 'BLSC:acercademi' %}" style="margin-left: 150px;">SOBRE MÍ</a>
                <a class="navbar-brand" href="{% url 'BLSC:home' %}" style="margin-left: 150px;">HOME</a>
                {% else %}
                <a class="navbar-brand" href="{% url 'BLSC:signin' %}" style="margin-left: 150px;">REGISTRATE</a>
                <a class="navbar-brand" href="{% url 'BLSC:login' %}" style="margin-left: 150px;">INICIÁ SESIÓN</a>
                <a class="navbar-brand" href="{% url 'BLSC:home' %}" style="margin-left: 150px;">BLOG</a>
                <a class="navbar-brand" href="{% url 'BLSC:acercademi' %}" style="margin-left: 150px;">SOBRE MÍ</a>
                <a class="navbar-brand" href="{% url 'BLSC:home' %}" style="margin-left: 150px;">HOME</a>
                {% endif %}                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                    </ul>
                </div>
            </div>
        </nav>    

    <!-- Page Content -->
    <div class="container">
        <h2></h2>
        <div class="row">
            <div class="col-md-6 col-lg-3">
                <div class="card">
                    <img src="{% static 'BLSC/imagenes/foto perfil circulo 2.png' %}" class="rounded-circle" width="250px">
                    <h3 class="card-title">Lucía Vallejos</h3>
                    <p class="card-text">Exploradora de Datos y Psicóloga en formación 📊🧠 | Apasionada por unir la ciencia de los datos con el entendimiento humano 🌐✨</p>
                    <p class="card-text">Podés seguirme o contactarme en mi cuenta de <a href="https://www.linkedin.com/in/lucia-vallejos-" target="_blank">LinkedIn</a></p>
                </div>
            </div>
            <div class="col">
                <div class="">
                    <div class="text-center">
                        <h2 style="text-align: center;">
                            <strong>¡Hola! Soy Lu 👋🏻<br></strong><br>
                        </h2>
                               📈 Actualmente me aventuro en el emocionante y desafiante mundo de los datos.<br>
                                
                               📚 Estudio Psicología, una disciplina que me dota de herramientas para acercarme a las personas<br></h1>
                                
                                de manera empática y analítica.<br>
                                
                                ➡️ Trabajo en el rubro de la traducción hace ya varios años<br>
                                
                                sin embargo actualmente me encuentro en una búsqueda activa por nuevos desafíos. <br>
                                
                                Busco ser parte de una organización que tenga como pilares la tecnología, la innovación,<br>
                                
                                el trabajo colaborativo, la mejora continua y el respeto interpersonal.<br>
                                
                                👉🏻 Soy creativa y con un perfil analítico. ¡Mi pasión por el aprendizaje constante me impulsa cada día!<br>
                                
                                Estoy entusiasmada por explorar oportunidades que me permitan fusionar mi formación en Psicología<br>
                                
                                con mi creciente interés en el análisis de datos.<br>
                                
                                ¡Gracias por echarle un ojo a mi proyecto!
                        </h2>                        
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'BLSC/js/scripts.js' %}"></script>
</body>
</html>

ProyectoFinal/BLSC/templates/BLSC/blog_pages.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>BLSC</title>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <style>
        /* Estilos CSS existentes aquí... */
    </style>
</head>

<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="{% url 'BLSC:home' %}" style="font-family: 'Open Sans', sans-serif; color: #fff;"><h5><strong>HOME</strong></h5></a>
            <!-- Puedes ajustar el color aquí según sea necesario -->

            <!-- Lista de enlaces -->
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'BLSC:listapoesias' %}" style="color: #080808;">POESÍAS</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'BLSC:listapoesias' %}" style="color: #fff;">FICCIÓN</a>
                </li>
                <!-- Agrega más enlaces según sea necesario -->
            </ul>
        </div>
    </nav>

    <!-- Resto de tu contenido -->
</body>
</html>

ProyectoFinal/BLSC/templates/BLSC/editarperfil.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>BLSC</title>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <style>
        body {
            background-image: url('{% static 'BLSC/img/pclibro.jpg' %}');
            background-size: cover;
            background-position: center;
            margin: 0;
            height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        nav {
            margin-bottom: auto;
        }

        h2 {
            text-align: center;
            color: #130f0f;
            font-family: 'Open Sans', sans-serif;
        }

        .card {
            max-width: 400px;
            width: 100%;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            text-align: center;
            transform: translateX(-50%);
            position: absolute;
            left: 50%;
        }

        .message {
            margin-bottom: 20px;
            font-family: 'Open Sans', sans-serif;
        }

        .btn-home {
            background-color: #007bff;
            color: #fff;
            border: none;
            padding: 10px 15px;
            border-radius: 4px;
            cursor: pointer;
            text-decoration: none;
        }

        .btn-home:hover {
            background-color: #0056b3;
        }
    </style>
</head>

<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
        <div class="container px-4 px-lg-5">
             <a class="navbar-brand" href="{% url 'BLSC:login' %}" style="font-family: 'Open Sans', sans-serif; color: #fff; margin-right: 180px"><h5><strong>INICIAR SESIÓN</strong></h5></a>
             <a class="navbar-brand" href="{% url 'BLSC:signin' %}" style="font-family: 'Open Sans', sans-serif; color: #fff; margin-right: 180px"><h5><strong>REGISTRATE</strong></h5></a>
             <a class="navbar-brand" href="{% url 'BLSC:acercademi' %}" style="font-family: 'Open Sans', sans-serif; color: #fff; margin-right: 180px"><h5><strong>SOBRE MÍ</strong></h5></a>
             <a class="navbar-brand" href="{% url 'BLSC:home' %}" style="font-family: 'Open Sans', sans-serif; color: #fff; margin-right: 180px"><h5><strong>HOME</strong></h5></a>
        </div>
    </nav>

    <div class="card">
        <h2><strong>Editar Perfil</strong></h2>
        <form action="{% url 'BLSC:editarperfil' %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn-home" value="Guardar Cambios">
        </form>
    </div>
</body>
</html>

ProyectoFinal/BLSC/templates/BLSC/home.html
{% extends 'BLSC/parent_template.html' %}


{% block contenido %}

{{ mensaje}}
{% endblock %}

ProyectoFinal/BLSC/templates/BLSC/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>BLSC</title>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <style>
        body {
            background-image: url('{% static 'BLSC/img/pclibro.jpg' %}');
            background-size: cover;
            background-position: center;
            margin: 0;
            height: 100vh;
            display: flex;
            flex-direction: column;
            align-items: stretch;
            justify-content: flex-start;
        }

        nav {
            margin-bottom: auto;
        }

        h2 {
            text-align: center;
            color: #fff;
            font-family: 'Open Sans', sans-serif;
        }

        form {
            max-width: 400px;
            width: 100%;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            margin: auto;
        }

        label {
            font-weight: bold;
            margin-bottom: 5px;
            color: #343a40;
        }

        .form-group {
            margin-bottom: 20px;
        }

        input[type="text"], input[type="password"], input[type="email"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ced4da;
            border-radius: 4px;
            box-sizing: border-box;
        }

        .error-list {
            color: red;
            list-style-type: none;
            margin: 0;
            padding: 0;
        }

        input[type="submit"] {
            background-color: #007bff;
            color: #fff;
            border: none;
            padding: 10px 15px;
            border-radius: 4px;
            cursor: pointer;
        }

        input[type="submit"]:hover {
            background-color: #0056b3;
        }
    </style>
</head>

<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
        <div class="container px-4 px-lg-5">
             <a class="navbar-brand" href="{% url 'BLSC:signin' %}" style="font-family: 'Open Sans', sans-serif; color: #fff; margin-right: 180px"><h5><strong>REGISTRATE</strong></h5></a>
             <a class="navbar-brand" href="{% url 'BLSC:home' %}" style="font-family: 'Open Sans', sans-serif; color: #fff; margin-right: 130px"><h5><strong>HOME</strong></h5></a>
             <a class="navbar-brand" href="{% url 'BLSC:acercademi' %}" style="font-family: 'Open Sans', sans-serif; color: #fff; margin-right: 100px"><h5><strong>SOBRE MÍ</strong></h5></a>
            <!-- Puedes ajustar el color aquí según sea necesario -->
        </div>
    </nav>

    <h2 style="text-align: center;">
        <strong>Iniciá sesión y disfrutá de interactuar con esta comunidad</strong><br>
        <strong>apasionada por la lectura.</strong>
    </h2>
    
    <form action="{% url 'BLSC:login' %}" method="POST">
        {% csrf_token %}

        {% for field in form %}
            <div class="form-group">
                <label style="font-family: 'Open Sans', sans-serif;">{{ field.label_tag }}</label>
                {{ field }}

                {% if field.errors %}
                    <ul class="error-list">
                        {% for error in field.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
        {% endfor %}

        <input type="submit" value="Iniciar sesión">
    </form>
</body>
</html>

ProyectoFinal/BLSC/templates/BLSC/parent_template.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>BLSC</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'BLSC/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>

<body>
        {% block contenido %}
        {% endblock contenido %}
</body>
</html>

        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                {% if user.is_authenticated %}
                <span class="navbar-text" style="color: white;">|En línea: {{ user.username }}|</span>
                <img src="{{ avatar_url }}" style="height: 40px; width: auto; border-radius: 50%; vertical-align: middle;"/>
                <a class="navbar-brand" href="{% url 'BLSC:editarperfil' %}" style="margin-left: 150px;">EDITAR PERFIL</a>            
                <a class="navbar-brand" href="{% url 'BLSC:logout' %}" style="margin-left: 50px;">CERRÁ SESIÓN</a>
                <a class="navbar-brand" href="{% url 'BLSC:home' %}" style="margin-left: 50px;">BLOG</a>
                <a class="navbar-brand" href="{% url 'BLSC:acercademi' %}" style="margin-left: 50px;">SOBRE MÍ</a>
                <a class="navbar-brand" href="{% url 'BLSC:home' %}" style="margin-left: 50px;">HOME</a>
                {% else %}
                <a class="navbar-brand" href="{% url 'BLSC:signin' %}" style="margin-left: 150px;">REGISTRATE</a>
                <a class="navbar-brand" href="{% url 'BLSC:login' %}" style="margin-left: 150px;">INICIÁ SESIÓN</a>
                <a class="navbar-brand" href="{% url 'BLSC:home' %}" style="margin-left: 150px;">BLOG</a>
                <a class="navbar-brand" href="{% url 'BLSC:acercademi' %}" style="margin-left: 150px;">SOBRE MÍ</a>
                <a class="navbar-brand" href="{% url 'BLSC:home' %}" style="margin-left: 150px;">HOME</a>
                {% endif %}                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                    </ul>
                </div>
            </div>
        </nav>

        {% block contenidoimagen %}         
                <!-- Page Header-->
        <header class="masthead" style="background-image: url('{% static 'BLSC/img/pclibro.jpg' %}'); background-size: cover; background-position: center center;">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading" style="padding-top: 180px; padding-bottom: 140px;">
                            {% block contenidocentro %}
                            <h1>Buena Lectura Social Club</h1>                        
                            <span class="subheading">Una comunidad reunida alrededor de la lectura y el debate. Participá de este blog compartiendo detalles de una lectura que te haya gustado o contanos sobre eso que leíste y no te atrapó.</span>
                            {% endblock contenidocentro %}
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% endblock contenidoimagen %}

        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'BLSC/js/scripts.js' %}"></script>